<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <RootNamespace>Yohuke.DanmuNeo</RootNamespace>
        <Company>Yohuke no Symphony</Company>
        <Product>Yohuke Danmu Neo</Product>
        <AssemblyVersion>0.0.2</AssemblyVersion>
        <FileVersion>0.0.2</FileVersion>
        <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Apis\Models\" />
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
        <EmbeddedResource Include="Assets\Player\mpegts.js" LogicalName="Yohuke.DanmuNeo.Assets.Player.mpegts.js" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12" />
        <PackageReference Include="Avalonia.Controls.WebView" Version="11.4.0" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
        <PackageReference Include="Lucide.Avalonia" Version="0.2.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="RestSharp" Version="114.0.0" />
        <PackageReference Include="RestSharp.Serializers.NewtonsoftJson" Version="114.0.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Yohuke.DanmuNeo.Tests" />
    </ItemGroup>
</Project>
